// packages/fe24/src/pages/dashboard/recursive-child.vue
<script setup lang="ts">
import type { IMenuItem } from "@/types/user";
import { name2icon } from "@/utils/icons";
import { useRouter } from "vue-router";

defineOptions({
  name: "RecursiveChild",
});

defineProps<{
  item: IMenuItem;
}>();

const router = useRouter();
const handleClick = (url: string) => {
  router.push(url);
};
</script>

<template>
  <main>
    <!-- gap: 70px -->
    <div v-if="item.children" class="flex justify-between gap-17.5">
      <RecursiveChild
        v-for="child of item.children"
        :key="child.url"
        :item="child"
      ></RecursiveChild>
    </div>

    <Component
      v-else
      :is="name2icon.get(item.icon)"
      class="text-[25px] transition-all duration-500 hover:scale-[2] hover:cursor-pointer"
      @click="handleClick(item.url)"
    ></Component>
  </main>
</template>

// packages/fe24-client/src/pages/dashboard/recursive-child.tsx
import React from 'react'
import { useNavigate } from 'react-router-dom'
import { name2icon } from '@/utils/icons'
import type { IMenuItem } from '@/types/user'

interface RecursiveChildProps {
  item: IMenuItem
}

const RecursiveChild: React.FC<RecursiveChildProps> = ({ item }) => {
  const navigate = useNavigate()

  if (item.children?.length) {
    return (
      <div className="flex justify-between gap-17.5">
        {item.children.map((child) => (
          <RecursiveChild key={child.url} item={child} />
        ))}
      </div>
    )
  }

  const IconComponent = name2icon.get(item.icon)
  if (!IconComponent) {
    return null
  }

  return (
    <div
      className="text-[25px] transition-all duration-500 hover:scale-[2] hover:cursor-pointer"
      onClick={() => navigate(item.url)}
    >
      <IconComponent />
    </div>
  )
}

export default RecursiveChild
