// packages/fe24-client/src/pages/main/components/robot-card.tsx
import React from 'react'
import { Tag } from 'antd'
import { ROBOT_STATE_2_TEXT_AND_TYPE } from '@/constants'
import robotSvg from '@/assets/robot.svg'

interface RobotCardProps {
  stateId: 0 | 1 | 2 | 3 | 4 | 5
  failureNum: number
  children?: React.ReactNode
}

const STATE_COLOR: Record<string, string> = {
  danger: 'red',
  success: 'green',
  warning: 'orange',
  info: 'blue',
}

const RobotCard: React.FC<RobotCardProps> = ({ stateId, failureNum, children }) => {
  const stateInfo = ROBOT_STATE_2_TEXT_AND_TYPE.get(stateId)
  const color = STATE_COLOR[stateInfo?.type || 'info'] ?? 'blue'

  return (
    <div
      className="grid h-55.5 w-83.25 items-center justify-center rounded-3xl! border-3 border-(--color-2nd) duration-1000 hover:scale-110"
      style={{ gridTemplateColumns: 'calc(100% / 3) calc(2 * (100% / 3))' }}
    >
      <div className="flex flex-col items-center justify-between">
        <Tag color={color} className="px-3 py-1 text-[15px]!">
          {stateInfo?.text}
        </Tag>
        <img src={robotSvg} alt="eva" width="70px" className="mt-4" />
        <p className="m-0 mt-4">零件故障数</p>
        <p className="m-0">{failureNum}</p>
      </div>

      <div>
        {children}
        <p style={{ color: failureNum > 50 ? '#fb2c36' : '#a1e3f9' }} className="m-0 mt-4">
          {failureNum > 50 ? '有预警 (零件故障数 > 50)' : '无预警 (零件故障数 <= 50)'}
        </p>
      </div>
    </div>
  )
}

export default RobotCard

// packages/fe24-client-vue/src/pages/main/components/robot-card.vue
<script setup lang="ts">
import { ROBOT_STATE_2_TEXT_AND_TYPE } from '@/constants'
import { toRefs } from 'vue'

const props = defineProps<{
  stateId: 0 | 1 | 2 | 3 | 4 | 5
  failureNum: number
}>()
const { stateId, failureNum } = toRefs(props)
</script>

<template>
  <div
    class="grid-layout border-2nd h-55.5 w-83.25 items-center justify-center rounded-3xl! border-3 duration-1000 hover:scale-110"
  >
    <div class="flex flex-col items-center justify-between">
      <ElTag
        size="large"
        :type="ROBOT_STATE_2_TEXT_AND_TYPE.get(stateId)?.type"
        class="text-[15px]!"
      >
        {{ ROBOT_STATE_2_TEXT_AND_TYPE.get(stateId)?.text }}
      </ElTag>
      <!-- todo: 图片懒加载 -->
      <img src="@/assets/robot.svg" alt="eva" width="70px" />
      <p>零件故障数</p>
      <p>{{ failureNum }}</p>
    </div>

    <!-- 默认插槽 -->
    <div>
      <slot name="default"></slot>
      <p :style="{ color: failureNum > 50 ? '#fb2c36' : '#a1e3f9' }">
        {{ failureNum > 50 ? '有预警 (零件故障数 > 50)' : '无预警 (零件故障数 <= 50)' }}
      </p>
    </div>
  </div>
</template>

<style scoped lang="scss">
.grid-layout {
  display: grid; // 网格布局
  // grid-template-columns: 1fr 2fr;
  grid-template-columns: calc(100% / 3) calc(2 * (100% / 3));
}
</style>
