// packages/fe24-client-vue/src/layouts/layout-tabs.vue
<script setup lang="ts">
import { ElWatermark } from 'element-plus'

import { useUserStore } from '@/stores/user'
defineProps<{
  watermarked: boolean
}>()
const userStore = useUserStore()
</script>

<template>
  <!--! <RouterView>, <Transition> or <KeepAlive>. Use slot props instead -->
  <ElWatermark
    :content="watermarked ? userStore.username : ''"
    :font="{ fontSize: 28, fontFamily: 'PingFang SC, Microsoft YaHei' }"
  >
    <RouterView v-slot="{ Component }">
      <!-- leave-active-class="animate__animated animate__fadeOutRight" -->
      <Transition enter-active-class="animate__animated animate__fadeInLeft">
        <!-- :include="[组件名数组]" -->
        <!-- 注意: tsx 文件需要在 defineComponent 时指定组件名 -->
        <KeepAlive :include="['FeRobot', 'OrderDetail']">
          <Component :is="Component"></Component>
        </KeepAlive>
      </Transition>
    </RouterView>
  </ElWatermark>
</template>

// packages/fe24-client/src/layouts/layout-tabs.tsx
import React from 'react'
import { Outlet, useLocation } from 'react-router-dom'
import { Watermark } from 'antd'
import { useUserStore } from '@/stores/user'
import 'animate.css'

interface LayoutTabsProps {
  watermarked: boolean
}

const LayoutTabs: React.FC<LayoutTabsProps> = ({ watermarked }) => {
  const { username } = useUserStore()
  const location = useLocation()

  return (
    <Watermark
      content={watermarked ? username : ''}
      font={{ fontSize: 28, fontFamily: 'PingFang SC, Microsoft YaHei' }}
      className="min-h-full"
    >
      <div
        key={location.pathname}
        className="animate__animated animate__fadeInLeft min-h-full w-full p-5"
      >
        <Outlet />
      </div>
    </Watermark>
  )
}

export default LayoutTabs
