// packages/fe24-client/src/components/aside/aside-menu.tsx
import React from 'react'
import { Menu } from 'antd'
import { Rice } from '@icon-park/react'
import { useLocation, useNavigate } from 'react-router-dom'
import { useUserStore } from '@/stores/user'
import RecursiveChild from './recursive-child'

const AsideMenu: React.FC = () => {
  const menuList = useUserStore((state) => state.menuList)
  const location = useLocation()
  const navigate = useNavigate()

  return (
    <div className="flex h-full flex-col overflow-hidden bg-white shadow-lg">
      <div
        className="flex h-16 cursor-pointer items-center justify-center gap-2.5 px-2.5"
        onClick={() => navigate('/')}
      >
        <Rice theme="filled" size={48} fill="#b8e986" strokeWidth={3} />
        <h1 className="m-0 text-[20px]">机器人</h1>
      </div>

      <div className="flex-1 overflow-y-auto" style={{ scrollbarWidth: 'none' }}>
        <Menu
          mode="inline"
          selectedKeys={[location.pathname]}
          className="border-none"
          theme="light"
        >
          {menuList.map((item) => (
            <RecursiveChild key={item.url} item={item} />
          ))}
        </Menu>
      </div>
    </div>
  )
}

export default AsideMenu

// packages/fe24-client-vue/src/components/aside/aside-menu.vue
<script setup lang="ts">
import { useUserStore } from '@/stores/user'
import { storeToRefs } from 'pinia'
import RecursiveChild from './recursive-child.vue'
import { ElMenu } from 'element-plus'
import { Rice } from '@icon-park/vue-next'
import { useRoute, useRouter } from 'vue-router'
import { computed } from 'vue'
import type { IMenuItem } from '@/types/user'

const userStore = useUserStore()
const { menuList } = storeToRefs(userStore)
const route = useRoute()
const router = useRouter()
const handleClick = () => router.push({ name: 'Home' })

const defaultOpeneds = computed(() => {
  const keys: string[] = []
  const findParent = (list: IMenuItem[], parentName?: string) => {
    for (const item of list) {
      if (item.url === route.path && parentName) {
        keys.push(parentName)
      }
      if (item.children) {
        findParent(item.children, item.name)
      }
    }
  }
  findParent(menuList.value)
  return keys
})
</script>

<template>
  <div>
    <div
      class="flex h-17.5 cursor-pointer items-center justify-center gap-2.5 px-2.5"
      @click="handleClick"
    >
      <Rice theme="filled" size="48" fill="#b8e986" :strokeWidth="3" />
      <h1 class="text-[20px]">机器人</h1>
    </div>

    <ElMenu
      class="menu-list border-none!"
      router
      :default-active="route.path"
      :default-openeds="defaultOpeneds"
    >
      <RecursiveChild v-for="item of menuList" :key="item.url" :item="item"></RecursiveChild>
    </ElMenu>
  </div>
</template>

<style scoped lang="scss">
.menu-list {
  :deep(.is-active) {
    background-color: var(--color-green) !important;
    color: #fff;
    font-size: 16px;
    transition: all;
  }
}

:deep(.el-menu-item) {
  border-radius: 20px;
  &:hover {
    background-color: var(--color-green-light) !important;
  }
}

:deep(.el-sub-menu__title) {
  &:hover {
    background-color: var(--color-green-light) !important;
  }
}
</style>
