// packages/fe24-client/src/components/common/virtual-list-item.tsx
import React from 'react'
import { commaSep } from '@/utils/comma-sep'
import type { IRevenueItem } from '@/types/dashboard'

interface VirtualListItemProps {
  item: IRevenueItem
  idx: number
}

const VirtualListItem: React.FC<VirtualListItemProps> = ({ item, idx }) => {
  return (
    <div
      className="flex h-full items-center"
      style={{ background: idx % 2 === 0 ? '#ecfcca' : '#fff' }}
    >
      <div className="w-[20%] text-center">{commaSep(item.revenue)}</div>
      <div className="w-[80%] truncate">{item.address}</div>
    </div>
  )
}

export default VirtualListItem

// packages/fe24/src/components/common/virtual-list-item.vue
<script setup lang="ts">
import { commaSep } from "@/utils/comma-sep.ts";
import type { IRevenueItem } from "@/types/dashboard";

defineProps<{
  item: IRevenueItem;
  idx: number;
}>();
</script>

<template>
  <div
    class="flex h-full items-center"
    :style="{
      background: idx % 2 === 0 ? '#ecfcca' : '#fff',
    }"
  >
    <div class="w-[20%] text-center">
      {{ commaSep(item.revenue) }}
    </div>
    <div class="w-[80%] truncate">
      {{ item.address }}
    </div>
  </div>
</template>

<style lang="scss" scoped>
.container::-webkit-scrollbar {
  display: none !important;
}
</style>
