// packages/fe24-client-vue/src/components/toast/toast-main.vue
<!-- 特点 -->
<!-- 1. 支持多种提示类型: success, error, warning, default -->
<!-- 2. 自定义显示时长 -->
<!-- 3. 防抖处理, 避免频繁调用 -->
<!-- 4. 优雅的动画效果 -->
<!-- 5. 自动清理资源 -->
<script setup lang="ts">
import { onBeforeUnmount, ref } from 'vue'
import { Attention, CheckOne, CloseOne, Caution } from '@icon-park/vue-next'

const props = defineProps<{
  message: string
  type: 'success' | 'error' | 'warning' | 'default'
  duration: number //! duration >= 500 && duration <= 2500, default 1500
}>()

const isAlive = ref(false)
let timer: number | null = null

// 资源清理
onBeforeUnmount(() => {
  if (timer) {
    clearTimeout(timer)
    timer = null
  }
})

/**
 * @description 节流 throttle (只触发第一次)
 */
const mount = () => {
  if (timer) {
    return
  }
  isAlive.value = true
  timer = setTimeout(() => {
    isAlive.value = false
    timer = null
  }, props.duration)
}

defineExpose({ mount, isAlive })
</script>

<template>
  <!-- enter-active-class="" leave-active-class="" -->
  <Transition name="fade">
    <div
      v-if="isAlive"
      class="border-1st fixed top-[10%] left-[50%] z-100 -translate-x-[50%] rounded-lg border-[3px] p-1.25"
    >
      <div class="flex items-center gap-1.25">
        <CheckOne theme="filled" size="24" fill="#7ed321" v-if="type === 'success'" />
        <CloseOne theme="filled" size="24" fill="#d0021b" v-else-if="type === 'error'" />
        <Caution theme="filled" size="24" fill="#f5a623" v-else-if="type === 'warning'" />
        <!-- type === 'default' -->
        <Attention theme="filled" size="24" fill="#4a90e2" v-else />
        <span>{{ message }}</span>
      </div>
    </div>
  </Transition>
</template>

<style scoped lang="scss">
.fade-enter-active,
.fade-leave-active {
  transition: opacity 1s ease;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}
</style>

// packages/fe24-client/src/components/toast/toast-main.tsx
import { useState, useEffect, useImperativeHandle, forwardRef, useRef } from 'react'
import { Attention, CheckOne, CloseOne, Caution } from '@icon-park/react'

export interface ToastMainProps {
  message: string
  type: 'success' | 'error' | 'warning' | 'default'
  duration: number //! duration >= 500 && duration <= 2500, default 1500
}

export interface ToastMainRef {
  mount: () => void
  isAlive: boolean
}

const ToastMain = forwardRef<ToastMainRef, ToastMainProps>((props, ref) => {
  const { message, type, duration } = props
  const [isAlive, setIsAlive] = useState(false)
  const timerRef = useRef<number | null>(null)

  useEffect(() => {
    return () => {
      if (timerRef.current) {
        window.clearTimeout(timerRef.current)
        timerRef.current = null
      }
    }
  }, [])

  const mount = () => {
    if (timerRef.current) {
      return
    }
    setIsAlive(true)
    timerRef.current = window.setTimeout(() => {
      setIsAlive(false)
      timerRef.current = null
    }, duration)
  }

  useImperativeHandle(ref, () => ({
    mount,
    get isAlive() {
      return isAlive
    },
  }))

  if (!isAlive) return null

  return (
    <div className="border-1st animate__animated animate__fadeIn animate__faster fixed top-[10%] left-[50%] z-100 -translate-x-[50%] rounded-lg border-[3px] p-1.25">
      <div className="flex items-center gap-1.25">
        {type === 'success' && <CheckOne theme="filled" size="24" fill="#7ed321" />}
        {type === 'error' && <CloseOne theme="filled" size="24" fill="#d0021b" />}
        {type === 'warning' && <Caution theme="filled" size="24" fill="#f5a623" />}
        {type === 'default' && <Attention theme="filled" size="24" fill="#4a90e2" />}
        <span>{message}</span>
      </div>
    </div>
  )
})

ToastMain.displayName = 'ToastMain'

export default ToastMain
