// packages/fe24-client/src/layouts/layout-main.tsx
import React, { useState, useRef, useEffect } from 'react'
import { Layout } from 'antd'
import AsideMenu from '@/components/aside'
import HeaderMain from '@/components/header'
import LayoutTabs from './layout-tabs'
import styles from './index.module.scss'
import bus from '@/utils/bus'

const { Header, Sider, Content } = Layout

const LayoutMain: React.FC = () => {
  const [watermarked, setWatermarked] = useState(false)
  const contentRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    const storeScrollTop = () => {
      if (contentRef.current) {
        sessionStorage.setItem('scroll-top', contentRef.current.scrollTop.toString())
        contentRef.current.scrollTop = 0
      }
    }
    const setScrollTop = () => {
      if (contentRef.current) {
        contentRef.current.scrollTop = Number.parseFloat(
          sessionStorage.getItem('scroll-top') || '0',
        )
      }
    }
    bus.subscribe('store-scrollTop', storeScrollTop)
    bus.subscribe('set-scrollTop', setScrollTop)
    return () => {
      bus.unsubscribe('store-scrollTop', storeScrollTop)
      bus.unsubscribe('set-scrollTop', setScrollTop)
    }
  }, [])

  return (
    <Layout className="h-screen overflow-hidden">
      <Sider width={200} theme="light" className="z-20 shadow-lg">
        <AsideMenu />
      </Sider>
      <Layout>
        <Header className={`${styles.header} z-10 flex h-[10vh] flex-col p-0`}>
          <HeaderMain onSwitchWatermark={setWatermarked} />
        </Header>
        <Content className="relative h-[90vh] overflow-auto bg-gray-50" ref={contentRef}>
          <LayoutTabs watermarked={watermarked} />
        </Content>
      </Layout>
    </Layout>
  )
}

export default LayoutMain

// packages/fe24/src/layouts/layout-main.vue
<script setup lang="ts">
import { ElContainer, ElHeader, ElAside, ElMain } from "element-plus";
import AsideMenu from "@/components/aside/aside-menu.vue";
import HeaderMain from "@/components/header/header-main.vue";
import LayoutTab from "./layout-tabs.vue";
import { onUnmounted, ref, useTemplateRef } from "vue";
import bus from "@/utils/bus";

const watermarked = ref(false);

const tabContainerRef =
  useTemplateRef<InstanceType<typeof ElMain>>("tabContainerRef");
const storeScrollTop = () => {
  sessionStorage.setItem(
    "scroll-top",
    tabContainerRef.value?.$el.scrollTop.toString(),
  );
  tabContainerRef.value!.$el.scrollTop = 0;
};
const setScrollTop = () => {
  tabContainerRef.value!.$el.scrollTop = Number.parseFloat(
    sessionStorage.getItem("scroll-top")!,
  );
};
bus.subscribe("store-scrollTop", storeScrollTop);
bus.subscribe("set-scrollTop", setScrollTop);

onUnmounted(() => {
  bus.unsubscribe("store-scrollTop", storeScrollTop);
  bus.unsubscribe("set-scrollTop", setScrollTop);
});
</script>

<template>
  <ElContainer>
    <ElAside class="h-dvh! w-50! bg-white shadow-lg">
      <AsideMenu></AsideMenu>
    </ElAside>
    <ElContainer>
      <ElHeader class="z-10 h-[10vh]! p-0!">
        <HeaderMain
          @switch-watermark="(isAlive: boolean) => (watermarked = isAlive)"
        ></HeaderMain>
      </ElHeader>
      <ElMain class="h-[90vh]!" ref="tabContainerRef">
        <LayoutTab :watermarked="watermarked"></LayoutTab>
      </ElMain>
      <!-- <ElBacktop :right="100" :bottom="100" /> -->
    </ElContainer>
  </ElContainer>
</template>

<style scoped lang="scss">
/** 隐藏滚动条 */
.el-aside::-webkit-scrollbar {
  display: none;
}
</style>
