// packages/fe24-client/src/components/common/progress-bar.tsx
import React, { useState, useImperativeHandle, forwardRef } from 'react'

export interface ProgressBarRef {
  loadStart: () => void
  loadEnd: () => void
}

const ProgressBar = forwardRef<ProgressBarRef>((_, ref) => {
  const [progress, setProgress] = useState(0)
  const requestIdRef = React.useRef<number>(0)

  const loadStart = () => {
    const fn = () => {
      setProgress((prev) => {
        if (prev < 100) {
          requestIdRef.current = window.requestAnimationFrame(fn)
          return prev + 1
        } else {
          window.cancelAnimationFrame(requestIdRef.current)
          return 0
        }
      })
    }
    requestIdRef.current = window.requestAnimationFrame(fn)
  }

  const loadEnd = () => {
    setTimeout(() => {
      requestIdRef.current = window.requestAnimationFrame(() => {
        setProgress(0)
      })
    }, 3000)
  }

  useImperativeHandle(ref, () => ({
    loadStart,
    loadEnd,
  }))

  return (
    <main className="fixed top-0 z-50 h-1.25 w-dvw">
      <div className="h-1.25 bg-(--color-green)" style={{ width: `${progress}%` }}></div>
    </main>
  )
})

ProgressBar.displayName = 'ProgressBar'

export default ProgressBar

// packages/fe24-client-vue/src/components/common/progress-bar.vue
<script setup lang="ts">
import { ref, computed } from 'vue'

const progress = ref(0)
const barWidth = computed(() => progress.value + '%')
let requestId = 0

const loadStart = () => {
  requestId = window.requestAnimationFrame(function fn() {
    if (progress.value < 100) {
      progress.value++
      requestId = window.requestAnimationFrame(fn)
    } else {
      progress.value = 0
      window.cancelAnimationFrame(requestId)
    }
  })
}

const loadEnd = () => {
  setTimeout(() => {
    requestId = window.requestAnimationFrame(() => {
      progress.value = 0
    })
  }, 3000)
}

defineExpose({
  loadStart,
  loadEnd,
})
</script>

<template>
  <main class="fixed top-0 h-1.25 w-dvw">
    <div ref="bar" class="bg-green bar h-1.25 w-0"></div>
  </main>
</template>

<style scoped lang="scss">
.bar {
  width: v-bind(barWidth);
}
</style>
